 
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- stage

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar cloud'
    organization: 'vishalmishra84'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'vishalmishra84_nodejs-ex'
    cliProjectName: 'nodejs-ex'
    cliSources: '.'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm test
  displayName: 'unit test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Unit Test'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift'
    cmd: 'oc project vishal-k-mishra-stage'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift'
    cmd: 'oc start-build nodejs-ex --follow'

- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift'
    cmd: 'oc status'
